name:                curry-language-server
version:             1.0.0.4
github:              "fwcd/curry-language-server"
license:             BSD3
author:              "fwcd"
copyright:           "2020-2024 fwcd"

synopsis:            IDE support for the functional-logic language Curry
category:            Development
description:         Please see the README on GitHub at <https://github.com/fwcd/curry-language-server#readme>

extra-source-files:
  - README.md

dependencies:
  - base            >= 4.16 && < 4.19
  - aeson           >= 2.0  && < 2.2
  - async           >= 2.2  && < 2.3
  - containers      >= 0.6  && < 0.7
  - data-default    >= 0.7  && < 0.8
  - extra           >= 1.7  && < 1.8
  - either          >= 5.0  && < 6
  - mtl             >= 2.2  && < 2.4
  - transformers    >= 0.5  && < 0.7
  - exceptions      >= 0.10 && < 0.11
  - stm             >= 2.5  && < 2.6
  - text            >= 2.0  && < 2.1
  - text-rope       >= 0.2  && < 0.3
  - lens            >= 5.1  && < 5.3
  - co-log-core     >= 0.3  && < 0.4
  - filepath        >= 1.4  && < 1.5
  - Glob            >= 0.10 && < 0.11
  - directory       >= 1.3  && < 1.4
  - sorted-list     >= 0.2  && < 0.3
  - lsp             >= 2.7  && < 2.8
  - unliftio-core   >= 0.2  && < 0.3
  - bytestring      >= 0.11 && < 0.12
  - bytestring-trie >= 0.2  && < 0.3
  - process         >= 1.6  && < 2
  - parsec          >= 3.1  && < 4
  - pretty          >= 1.1  && < 1.2
  - curry-frontend

library:
  source-dirs: src
  ghc-options:
    - -Wall

executables:
  curry-language-server:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
    dependencies:
      - curry-language-server

tests:
  curry-language-server-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - curry-language-server
