#!/usr/bin/env python3

from pathlib import Path

import argparse
import platform
import shutil
import subprocess
import zipfile

ROOT_DIR = Path(__file__).resolve().parent.parent

def main():
    parser = argparse.ArgumentParser(description='Creates a binary distribution of the language server')
    parser.add_argument('-f', '--format', type=str, default='zip' if platform.system() == 'Windows' else 'gztar', help='The format of the output archive.')
    parser.add_argument('-o', '--output', type=Path, default=ROOT_DIR / 'bindists' / f'curry-language-server-{platform.machine().lower()}-{platform.system().lower()}', help='The name of the output archive.')

    args = parser.parse_args()
    format: str = args.format
    output: Path = args.output

    output.mkdir(parents=True, exist_ok=True)
    
    print('==> Building...')
    subprocess.run(['stack', 'install', '--local-bin-path', output / 'bin'], check=True, cwd=ROOT_DIR)

    print('==> Packaging...')
    shutil.copy('LICENSE', output)

    print('==> Archiving...')
    shutil.make_archive(output, format, output.parent, output.name)

if __name__ == '__main__':
    main()
