name: Linux

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Haskell and Stack
      uses: actions/setup-haskell@v1.1
      with:
        ghc-version: '8.6.5' # matches the lts-14.22 declared in stack.yaml
        enable-stack: true
        stack-version: 'latest'
    - name: Build
      run: stack build
